 4 999
Taxon1    CGTGCCTAGCCACTGTATTCGGCAGGGACGGAGTTTCGCCCGGTGACCCATACGAGGGCA
Taxon2    CGTTTTTAGTGACTATTTTTTGCACCAACCGTCTCGGGTCCGTAGACCGAGTCCAGGGCT
Taxon3    TGCATCCTTATACTAATACGGTCCCGTTCCTTCACGCATACGCGACCTGCCTCAACAGAC
Taxon4    TGGGTTTAACTGATGATACATACAGTCCCTATGATAGATACGCAGCATGGCCGCAGCTAG

          CAGGCGACATCTAAGCCCGGAACGGACACAGATGGCATCTATGGTTCATACCTGCCTGCC
          GAGGTAACAACTTAGCCATATAAGAACACAGATGGCCCTTCAGGTTTACCCCGGCCGCCC
          CATATACCTGGGATACCCATTAAGCGCAGAACGTGCACATCCTTTGGTAAGCACCTCGAT
          TAAAACACCAAATTTCCGATTCAGTGCTCCAGCGTAACATCCATGGGTCCCCACTTCGTT

          AGCATCAGGGAGTGAGAAACTATGGTGCGCCGTATTAAACCGATCATACTTACTGCCTCG
          AGCACTAGGGCGTAATAAAATATGGTGCGCCGTATTATAAAAAGCATACATACTCGCTCG
          GTGTCCTTCCCATAAAAATTAATGCCGTTTCGTTGTTCGAAGACATAAACAGTGAGGTCA
          AACTCGCTCTTAGATGGTGATAATGAGTATCCTATCATAAAGACAGAAAGCATGACTTAG

          TTCTCATATCCCCGTCAACGGTCTCTACATCGAGGCAACAAGTTTGCATGAATAGACAGA
          TTCGCGTAACCCCGTCTACATAGTCCTCCCAGACGCAATAAGGCTCCATGAATCGAGAAT
          TTCTGAGAAGCCCGAGTGTATTTTGAGGTCACGGATTAAATCTGTTCCTCGAAGGTCTAC
          TTATCAGAATTCAAGCATCAAGTTTATCTTATCTAATGGCTTTGTTGAGAACACGTTCAA

          AGAAACGCCGAATCAACCTTCACGAAACTCATGTAGTAATAGTCGTTACTAAACAGCAAG
          GGCGATGCCGAATCATGCTTCGCAAAACTTTTGTAGTAATGGGCCTTACTAGACTGTCGT
          GGCGGAGCTCCGTCACTCTACCCCACACCTCTGTAGAAGTGACAATTAGCCGCCTGTCAT
          GGCAGATCGGAGTAACGTCACCCTGCAGTTTTCAAGAAATCGTTTGCTCCGCCCAGGCGT

          CCTCCTGCTTTCAAACGAGGTCTATCCGTCCGAGTGCGGCAGCGCTACGATCGTAGGTGG
          CCTCCTCTCTTCAAACGAGGACCATCCGTACAAGTGACGGAGTGCTACGATCATGGGTGG
          CGCCACCCATCTAACGGACCTGGTGTCCATCGCGTCAGGCTTTACGTCGACCCGACCTGG
          CGTTACCCCTCTAACAGAACTACTTAAGAAGTCCTGCTGGTCATTGCGAAACAGACTTCG

          TAAGCGGCTGGCTGGTGTGATGGGCAGTGGTGGTCAGAGGGGGCCGTGAAGCTAAAATTT
          TAATCCACTGGTTGGTGTGGTGGGCATTGGCGCTCGGAGGTGTACATGAAGCTAAAAATT
          ATAGCGCCAGAACAGCACGTTGAACAGCGTAGCCCAACTAGCTGAATGCAGCTCGAAATG
          CTAACTCCCGACTAGCGGGAAAGGCAGAATGACAGGGCCGGACATTTGCTCCATAAAACG

          ATTCTCACACAGAGGTCTTTCCACCCCTTAGTACCGCGTGACGGTAACAGGTACGTTTGA
          TTCTTCAAATAAAGGGTTTATGTTCCCGCCCGAACACGTGACGGTTTCAGGTACGAATGA
          AGTTAGAACGCGCGCTTTTACATTACCGGATCGCTACTTGGGACCAGCGAGGGTCACCAC
          TCATACAGCGACCTCCCTAGCGCTGACGGAACAGTATGTTTGGGCGGCATGTATGACTAC

          AACTCGTCCTTAGACGGAGGTGCAAAATACCACAAAGCTTTCCTCCTTCGATGAGACAAC
          AACTCTTAGGTAAACGTAAGTGCTTGAGTCCACGCACAGTTCCTTCCTCTCTATGGCAAC
          ATCCAATACTTAAACAGTAGTGCACTTTCTAATAGATTACTCCTGCATGTGTACTTGTAG
          AACGAATAGCTAACACCAAGAGTACTACATGAATAAAAATCAGGTCTACTGTCCCGCAAG

          GTCACGGTAATTGCGACAGCGGGATCCTAAAATTTTCGATATTGTTATGAAAAAGGGCAT
          TACACGATACTCGCGACATCGCGCACCCAAAATAGTCGATATTGTTAGGCTAACGATAAA
          TGCTTAAGTGGCTCGCCTGCGGTCAAAAAAAAGCTCCGTCGAACGTATAGGACGACTAAG
          TTCCTCAGAGACTAGCCCTTGATGAAGGGCAAGGGGCGAATGATTTGTTAGACACCGAAA

          CGGATCCTTATCCGAGCGTATTCCTCTCGTCGCAGATGGCGGTTAGATGCGTATGTATAT
          CGGATCTTTAAATGAGTGTACACCTCTAGTCGACGGTGACGCTTACACGGGGATATCGAT
          TGGGGCGTATCATAAATGTACCCAACCTGTCTACGGTCCTCCTCACATGTGGAAGTGTCG
          TACGCCGGTCCTTAAAAGTTAGCGGCTTGGCCCCGATTAGTCTCAAAAGAGGCAATGTAG

          ACATGAATGCGAACGCCTGTACCGTTACTGTTGTAACCTAACTTTCGGTGACTCCCGTTC
          ACACTTATCAGGACGCCTGTACCGTTGCGGGCCAAACCAAACTCTGGGCGAGGCCCGGTC
          ATACTGTTCTATACACATTTAGCGGTTGTGCACAACACGTAGAGGGAATGGCTGCACCGC
          ACACTGTTCTACCCATCCGTACGGCTGCTGCACAAATAGGACACCGATTACCTGCTGCGC

          AACGTAACTCTAACAGCGACGCGCGAGGCAAGGGCTAGATCTACAGAACACCCTGCTTCG
          AACGTAACCCTAAGAGCGACACCTGACGCTAGGGCTAAATGTTCACCACACCCGGCTACA
          ATAGTGAATTCTAAAGCGATTGACTCTAACAGTGCATGCTGACGCCGACATGGGACCACG
          ACCGTTACTTCGGAAGCCATTAACTCAAACAGTGTACGAATGCGTCGATGGTGTTCCAGG

          CGCTTAGCAATGACGCTGACACTCAGGCGGGCCTATTATGGCAAAGCATCCTAGACGAAC
          GGCTGAGCCATTACGCTAACACTCAGTCAGGCTTACTACAGCAATCTTGTCCAGACGAAC
          TGGACTACTATCATGTTTAGATAACGGTAGAATGGTCACAGCCTGCCTTTCGGCCCCAAG
          GTAAGGACTAGCGTGCACGCTATGATTGGCAATTGTCGCCTCCTACCTTCAGCCGCCAAG

          ATTTGTCGCGTAGTGATCGCTTGTCCCGCTTAGTGTCTACTCCGATACTATTAGCCCAGC
          AGTAGTCGCGTCGTGCTCGCTTTAGCTGCTTAGAATCTATCATAATACTATGAGCCCAGC
          GCGCTTTGCTTCGTGGACGATGTTCATCTTAAGTATTGATACAGATTGTACGGGTCTGAC
          TAGTACCGCAACGGGCACAATGGGCTTGTTACAGGCAGATTGTAATTGTATGGTCCCCGA

          CGCCAAGTTCCTACCTCGGTAGGCTCGTATATATCGATGTTATCACTGACGAGCCGGGAT
          CGAATAATTCAGTGAGTGTTAGGCTCGTCTATATGGATGTCCCCACTAACGAGCTGTGAT
          GGGATGGCTATTTACTTCGCTTACCCGTCTCGTAGGAAAGAACGAGAAATTGCTCATACT
          GGGATGGATACTCTATTACCAAAACACTACACTAGGCGAATACCCATACTTACTTTCGTT

          GCTCATGCTCGACTGCACGCTGATTTGGACATGAAGCGA
          CCTGATGGGCGTCCGCACGCTGGCTTCGTCTTGCCGGGA
          TGCCTTGTTAGAGTCCAGCACGCATTCGTCGAGGCCTAA
          CGCCATGGTCGTGTCCAGGCGGCTCTCGCTGGAGCCTAA

